POST https://contabilizador-de-rifas.onrender.com/rifas
Content-Type: application/json

{
    "nome": "Jose",
    "numero": 123,
    "pagamento": "pendente"
}

###
GET https://contabilizador-de-rifas.onrender.com/rifas
###
PUT https://contabilizador-de-rifas.onrender.com/rifas/123
Content-Type: application/json

{
    "nome": "Dudu 2",
    "numero": 789,
    "pagamento": "ok"
}

###

DELETE https://contabilizador-de-rifas.onrender.com/rifas/789