POST http://localhost:3333/rifas
Content-Type: application/json

{
    "nome": "Dudu",
    "numero": 456,
    "pagamento": "pendente"
}

###
GET http://localhost:3333/rifas
###
PUT http://localhost:3333/rifas/123
Content-Type: application/json

{
    "nome": "Dudu",
    "numero": 123,
    "pagamento": "pendente"
}

###

DELETE http://localhost:3333/rifas/123